s/kairo_image_surface_get_surface/cairo_glib_image_surface_get_surface/g
s/KairoAntiAlias/cairo_anti_alias_t/g
s/KAIRO_/CAIRO_/g
s/KairoContent/cairo_content_t/g
s/KairoContext/cairo_t/g
s/KairoFillRule/cairo_fill_rule_t/g
s/KairoFormat/cairo_format_t/g
s/KairoImageSurface/cairo_image_surface_t/g
s/KairoLineCap/cairo_line_cap_t/g
s/KairoLineJoin/cairo_line_join_t/g
s/KairoOperator/cairo_operator_t/g
s/KairoPattern/cairo_pattern_t/g
s/KairoStatus/cairo_status_t/g
s/KairoSurface/cairo_surface_t/g
s/kairo_context/cairo/g
s/kairo_surface/cairo_surface/g
s/kairo_image_surface/cairo_image_surface/g
s/cairo_image_surface_get_type/kairo_image_surface_get_type/g
s/cairo_surface_get_type/kairo_surface_get_type/g
s/cairo_get_type/kairo_context_get_type/g
# GLib API changes
s/cairo_get_status/cairo_status/g
