# All enum members should go into our namespace

s/CAIRO_/KAIRO_/g

# But do not rename CAIRO_HAS_FEATURE_* macros

s/KAIRO_HAS_/CAIRO_HAS_/g

# Rename enums

s/cairo_anti_alias_t/KairoAntiAlias/g
s/cairo_content_t/KairoContent/g
s/cairo_fill_rule_t/KairoFillRule/g
s/cairo_format_t/KairoFormat/g
s/cairo_line_cap_t/KairoLineCap/g
s/cairo_line_join_t/KairoLineJoin/g
s/cairo_operator_t/KairoOperator/g
s/cairo_status_t/KairoStatus/g

# Cairo Pattern

s/cairo_pattern_t/KairoPattern/g

# Cairo Context

s/cairo_t/KairoContext/g
s/cairo_create/kairo_context_create/g
s/cairo_reference/kairo_context_reference/g
s/cairo_destroy/kairo_context_destroy/g
s/cairo_status/kairo_context_status/g
s/cairo_save/kairo_context_save/g
s/cairo_restore/kairo_context_restore/g
s/cairo_get_target/kairo_context_get_target/g
s/cairo_push_group/kairo_context_push_group/g
s/cairo_push_group_with_content/kairo_context_push_group_with_content/g
s/cairo_pop_group/kairo_context_pop_group/g
s/cairo_pop_group_to_source/kairo_context_pop_group_to_source/g
s/cairo_get_group_target/kairo_context_get_group_target/g
s/cairo_set_source_rgb/kairo_context_set_source_rgb/g
s/cairo_set_source_rgba/kairo_context_set_source_rgba/g
s/cairo_set_source/kairo_context_set_source/g
s/cairo_set_source_surface/kairo_context_set_source_surface/g
s/cairo_get_source/kairo_context_get_source/g
s/cairo_set_antialias/kairo_context_set_antialias/g
s/cairo_get_antialias/kairo_context_get_antialias/g
s/cairo_set_dash/kairo_context_set_dash/g
s/cairo_get_dash_count/kairo_context_get_dash_count/g
s/cairo_get_dash/kairo_context_get_dash/g
s/cairo_set_fill_rule/kairo_context_set_fill_rule/g
s/cairo_get_fill_rule/kairo_context_get_fill_rule/g
s/cairo_set_line_cap/kairo_context_set_line_cap/g
s/cairo_get_line_cap/kairo_context_get_line_cap/g
s/cairo_set_line_join/kairo_context_set_line_join/g
s/cairo_get_line_join/kairo_context_get_line_join/g
s/cairo_set_line_width/kairo_context_set_line_width/g
s/cairo_get_line_width/kairo_context_get_line_width/g
s/cairo_set_miter_limit/kairo_context_set_miter_limit/g
s/cairo_get_miter_limit/kairo_context_get_miter_limit/g
s/cairo_set_operator/kairo_context_set_operator/g
s/cairo_get_operator/kairo_context_get_operator/g
s/cairo_set_tolerance/kairo_context_set_tolerance/g
s/cairo_get_tolerance/kairo_context_get_tolerance/g
s/cairo_clip/kairo_context_clip/g
s/cairo_clip_preserve/kairo_context_clip_preserve/g
s/cairo_clip_extents/kairo_context_clip_extents/g
s/cairo_reset_clip/kairo_context_reset_clip/g
s/cairo_rectangle_list_destroy/kairo_context_rectangle_list_destroy/g
s/cairo_copy_clip_rectangle_list/kairo_context_copy_clip_rectangle_list/g
s/cairo_fill/kairo_context_fill/g
s/cairo_fill_preserve/kairo_context_fill_preserve/g
s/cairo_fill_extents/kairo_context_fill_extents/g
s/cairo_in_fill/kairo_context_in_fill/g
s/cairo_mask/kairo_context_mask/g
s/cairo_mask_surface/kairo_context_mask_surface/g
s/cairo_paint/kairo_context_paint/g
s/cairo_paint_with_alpha/kairo_context_paint_with_alpha/g
s/cairo_stroke/kairo_context_stroke/g
s/cairo_stroke_preserve/kairo_context_stroke_preserve/g
s/cairo_stroke_extents/kairo_context_stroke_extents/g
s/cairo_in_stroke/kairo_context_in_stroke/g
s/cairo_copy_page/kairo_context_copy_page/g
s/cairo_show_page/kairo_context_show_page/g
s/cairo_get_reference_count/kairo_context_get_reference_count/g
s/cairo_set_user_data/kairo_context_set_user_data/g
s/cairo_get_user_data/kairo_context_get_user_data/g
s/cairo_translate/kairo_context_translate/g
s/cairo_scale/kairo_context_scale/g
s/cairo_rotate/kairo_context_rotate/g
s/cairo_transform/kairo_context_transform/g
s/cairo_set_matrix/kairo_context_set_matrix/g
s/cairo_get_matrix/kairo_context_get_matrix/g
s/cairo_identity_matrix/kairo_context_identity_matrix/g
s/cairo_user_to_device/kairo_context_user_to_device/g
s/cairo_user_to_device_distance/kairo_context_user_to_device_distance/g
s/cairo_device_to_user/kairo_context_device_to_user/g
s/cairo_device_to_user_distance/kairo_context_device_to_user_distance/g
s/cairo_copy_path/kairo_context_copy_path/g
s/cairo_copy_path_flat/kairo_context_copy_path_flat/g
s/cairo_path_destroy/kairo_context_path_destroy/g
s/cairo_append_path/kairo_context_append_path/g
s/cairo_has_current_point/kairo_context_has_current_point/g
s/cairo_get_current_point/kairo_context_get_current_point/g
s/cairo_new_path/kairo_context_new_path/g
s/cairo_new_sub_path/kairo_context_new_sub_path/g
s/cairo_close_path/kairo_context_close_path/g
s/cairo_arc/kairo_context_arc/g
s/cairo_arc_negative/kairo_context_arc_negative/g
s/cairo_curve_to/kairo_context_curve_to/g
s/cairo_line_to/kairo_context_line_to/g
s/cairo_move_to/kairo_context_move_to/g
s/cairo_rectangle/kairo_context_rectangle/g
s/cairo_glyph_path/kairo_context_glyph_path/g
s/cairo_text_path/kairo_context_text_path/g
s/cairo_rel_curve_to/kairo_context_rel_curve_to/g
s/cairo_rel_line_to/kairo_context_rel_line_to/g
s/cairo_rel_move_to/kairo_context_rel_move_to/g
s/cairo_path_extents/kairo_context_path_extents/g

# Image Surface

s/cairo_image_surface_t/KairoImageSurface/g
s/cairo_image_surface_create/_cairo_image_surface_create/g
s/cairo_image_surface/kairo_image_surface/g

# Surface

s/cairo_surface_t/KairoSurface/g
s/cairo_surface/kairo_surface/g

# Everything else

s/cairo_/kairo_/g
